#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <algorithm>
#include <complex>
#include <vector>

#include "sirius/real_fft.hpp"

using namespace sirius;
using Catch::Matchers::WithinAbs;

namespace {
    template <typename Real>
    TensorXr<Real, 3> sequentialVolume(int nz, int ny, int nx) {
        TensorXr<Real, 3> x(nz, ny, nx);
        Real v = Real(0);
        for (Eigen::Index i = 0; i < x.size(); ++i)
            x.data()[i] = v++;
        return x;
    }

    template <typename Real>
    Real maxAbsDiff(const TensorXr<Real, 3>& a, const TensorXr<Real, 3>& b) {
        Real err = Real(0);
        for (Eigen::Index i = 0; i < a.size(); ++i)
            err = std::max(err, std::abs(a.data()[i] - b.data()[i]));
        return err;
    }
}

TEST_CASE("HalfComplexBand owns explicit (nz, ny, nx/2+1) storage", "[real_fft]") {
    HalfComplexBand<double> band(5, 7, 8);

    REQUIRE(band.nz() == 5);
    REQUIRE(band.ny() == 7);
    REQUIRE(band.nx() == 8);
    REQUIRE(band.halfNx() == 5);
    REQUIRE(band.tensor().dimension(0) == 5);
    REQUIRE(band.tensor().dimension(1) == 7);
    REQUIRE(band.tensor().dimension(2) == 5);
    REQUIRE(band.size() == 5 * 7 * 5);
}

TEST_CASE("RealFFT rfft matches NumPy/proto half-complex fixture", "[real_fft][numpy]") {
    // Fixture generated by:
    // np.fft.rfftn(np.arange(16, dtype=np.float64).reshape(2, 2, 4))
    const std::vector<std::complex<double>> expected = {
        {120.0, 0.0}, {-8.0, 8.0}, {-8.0, 0.0},
        {-32.0, 0.0}, {0.0, 0.0}, {0.0, 0.0},
        {-64.0, 0.0}, {0.0, 0.0}, {0.0, 0.0},
        {0.0, 0.0}, {0.0, 0.0}, {0.0, 0.0},
    };

    RealFFT fft({2, 2, 4}, 1, PlanRigor::Estimate);
    auto input = sequentialVolume<double>(2, 2, 4);
    HalfComplexBand<double> out(2, 2, 4);

    fft.rfft(input, out.tensor());

    REQUIRE(out.size() == static_cast<Eigen::Index>(expected.size()));
    for (Eigen::Index i = 0; i < out.size(); ++i) {
        CHECK_THAT(out.data()[i].real(), WithinAbs(expected[static_cast<std::size_t>(i)].real(), 1e-12));
        CHECK_THAT(out.data()[i].imag(), WithinAbs(expected[static_cast<std::size_t>(i)].imag(), 1e-12));
    }
}

TEST_CASE("RealFFT round trip recovers real volume", "[real_fft]") {
    RealFFT fft({3, 4, 6}, 1, PlanRigor::Estimate);
    auto input = sequentialVolume<double>(3, 4, 6);
    HalfComplexBand<double> freq(3, 4, 6);
    TensorXr<double, 3> recovered(3, 4, 6);

    fft.rfft(input, freq.tensor());
    fft.irfft(freq.tensor(), recovered, /*normalize=*/true);

    REQUIRE(maxAbsDiff(input, recovered) < 1e-10);
}

TEST_CASE("FFTW thread count API validates and stores planner thread count", "[real_fft][threads]") {
    REQUIRE_THROWS_AS(setFFTWThreadCount(0), std::invalid_argument);
    REQUIRE_NOTHROW(setFFTWThreadCount(1));
    REQUIRE(getFFTWThreadCount() == 1);
}
