# Writes the build's identity into a header, run as a script at every build
# (app/CMakeLists.txt: the sirius_build_info_header target):
#
#   cmake -DSOURCE_DIR=<tree> -DOUTPUT=<header> -DVERSION=<x.y.z>
#         -DSCHEMA_FILE=<op_schema.json> [-DGIT_EXECUTABLE=<git>]
#         [-DCOMMIT=<sha> -DDIRTY=0|1] -P BuildInfo.cmake
#
# The commit and whether the tree had changes come from git; COMMIT / DIRTY
# override that for a tree without .git (a container build from an archive).
# The operation schema hash is SHA-256 of the committed snapshot of every
# operation's parameters (bindings/python/sirius/op_schema.json, line endings
# normalised), which tests/test_app_engine.cpp holds equal to what the
# registry exports. It is the build's IDENTITY, not the application/engine
# compatibility key -- that is kOpsGeneration in app/core/build_info.hpp,
# which is a hand-maintained C++ constant and so is not written here. The
# header is rewritten only when its text changes, so an unchanged tree
# recompiles nothing.

if(NOT DEFINED OUTPUT OR NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "BuildInfo.cmake: OUTPUT and SOURCE_DIR are required")
endif()

set(_commit "")
set(_describe "")
set(_dirty 0)
if(DEFINED COMMIT AND NOT COMMIT STREQUAL "")
    set(_commit "${COMMIT}")
    string(SUBSTRING "${_commit}" 0 7 _describe)
    set(_describe "g${_describe}")
    if(DEFINED DIRTY AND DIRTY)
        set(_dirty 1)
    endif()
elseif(GIT_EXECUTABLE AND EXISTS "${SOURCE_DIR}/.git")
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse HEAD
                    OUTPUT_VARIABLE _commit RESULT_VARIABLE _rc OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(NOT _rc EQUAL 0)
        set(_commit "")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=7 HEAD
                    OUTPUT_VARIABLE _short RESULT_VARIABLE _rc OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_rc EQUAL 0)
        set(_describe "g${_short}")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
                    OUTPUT_VARIABLE _status RESULT_VARIABLE _rc OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_rc EQUAL 0 AND NOT _status STREQUAL "")
        set(_dirty 1)
    endif()
endif()
if(_commit STREQUAL "")
    set(_commit "unknown")
    set(_describe "unknown")
endif()

set(_schema "unknown")
if(DEFINED SCHEMA_FILE AND EXISTS "${SCHEMA_FILE}")
    file(READ "${SCHEMA_FILE}" _text)
    string(REPLACE "\r\n" "\n" _text "${_text}")
    string(SHA256 _schema "${_text}")
endif()

set(_build "${VERSION}+${_describe}")
if(_dirty)
    set(_build "${_build}.dirty")
endif()

set(_header "// Generated by cmake/BuildInfo.cmake at build time: do not edit.
#define SIRIUS_BUILD_VERSION \"${VERSION}\"
#define SIRIUS_BUILD_ID \"${_build}\"
#define SIRIUS_BUILD_COMMIT \"${_commit}\"
#define SIRIUS_BUILD_DIRTY ${_dirty}
#define SIRIUS_BUILD_OPS_SCHEMA \"${_schema}\"
")
set(_old "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
endif()
if(NOT _old STREQUAL _header)
    file(WRITE "${OUTPUT}" "${_header}")
endif()
