# Writes a text file into a header as a byte array, run as a script whenever
# the file changes (app/CMakeLists.txt: the worker's launch script):
#
#   cmake -DINPUT=<file> -DOUTPUT=<header> -DNAME=<identifier> -P EmbedText.cmake
#
# The header defines `static const unsigned char <NAME>[]` (no terminating
# zero) and `<NAME>_size`. Carriage returns are dropped: the text runs on a
# cluster's bash, whatever the checkout's core.autocrlf did to it. A byte
# array, not a string literal, so its length is not limited by the compiler.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED NAME)
    message(FATAL_ERROR "EmbedText.cmake: INPUT, OUTPUT and NAME are required")
endif()

file(READ "${INPUT}" _hex HEX)
string(REGEX MATCHALL "[0-9a-f][0-9a-f]" _bytes "${_hex}")
list(REMOVE_ITEM _bytes "0d")
list(LENGTH _bytes _size)
set(_body "")
set(_line "")
set(_n 0)
foreach(_b IN LISTS _bytes)
    string(APPEND _line "0x${_b},")
    math(EXPR _n "${_n} + 1")
    if(_n EQUAL 24)
        string(APPEND _body "    ${_line}\n")
        set(_line "")
        set(_n 0)
    endif()
endforeach()
if(NOT _line STREQUAL "")
    string(APPEND _body "    ${_line}\n")
endif()

set(_header "// Generated by cmake/EmbedText.cmake from ${INPUT}: do not edit.
static const unsigned char ${NAME}[] = {
${_body}};
static const unsigned long long ${NAME}_size = ${_size}ULL;
")
set(_old "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
endif()
if(NOT _old STREQUAL _header)
    file(WRITE "${OUTPUT}" "${_header}")
endif()
