import os
from pathlib import Path

if os.name == "nt":
    os.add_dll_directory(str(Path(__file__).parent))
    # CUDA-enabled wheels link to the user's toolkit, matching native CUDA
    # applications. Python 3.8+ no longer searches PATH for dependent DLLs,
    # so explicitly register CUDA_PATH/bin when the toolkit is installed.
    cuda_path = os.environ.get("CUDA_PATH")
    if cuda_path:
        for cuda_bin in (Path(cuda_path) / "bin", Path(cuda_path) / "bin" / "x64"):
            if cuda_bin.is_dir():
                os.add_dll_directory(str(cuda_bin))

from sirius._sirius_ext import (
    FFT,
    ApodizationType,
    BlendMode,
    Buffer,
    Device,
    DeviceProperties,
    DeviceType,
    ImageJMetadata,
    MaskedNccOptions,
    OmeChannel,
    OmeImage,
    OmeTiffData,
    PixelType,
    PlanRigor,
    SimFit,
    SIMParameters,
    SimReconstructor,
    StitchLayout,
    StitchOptions,
    Stream,
    TiffChannel,
    TiffCompression,
    TiffFile,
    TiffImageInfo,
    TiffInfo,
    TiffLayout,
    TiffLevel,
    TiffMetadata,
    TileMatch,
    TranslationResult,
    built_with_cuda,
    built_with_nvtiff,
    cuda_available,
    cuda_device_count,
    default_device,
    device_properties,
    device_request_problem,
    fuse_tiles,
    inspect_tiff,
    load_legacy_parameters,
    load_parameters,
    masked_ncc,
    next_fast_fft_size,
    ome_image_pages,
    optimize_tile_positions,
    parse_tiff_metadata,
    plan_stitch,
    read_tiff,
    register_tile_pair,
    register_translation_masked,
    save_parameters,
    sim_declared_counts_note,
    sim_image_size_problem,
    sim_layout_counts_problem,
    stitch_tiff_tiles,
    synchronize_device,
    to_device,
    write_tiff,
)

__all__ = [
    "Buffer",
    "ApodizationType",
    "Device",
    "DeviceProperties",
    "DeviceType",
    "FFT",
    "SIMParameters",
    "SimFit",
    "SimReconstructor",
    "PixelType",
    "PlanRigor",
    "Stream",
    "TiffCompression",
    "TiffFile",
    "TiffImageInfo",
    "TiffInfo",
    "TiffLayout",
    "TiffLevel",
    "TiffMetadata",
    "TiffChannel",
    "OmeImage",
    "OmeChannel",
    "OmeTiffData",
    "ImageJMetadata",
    "parse_tiff_metadata",
    "ome_image_pages",
    "built_with_cuda",
    "built_with_nvtiff",
    "cuda_available",
    "cuda_device_count",
    "default_device",
    "device_properties",
    "device_request_problem",
    "inspect_tiff",
    "load_legacy_parameters",
    "load_parameters",
    "read_tiff",
    "synchronize_device",
    "save_parameters",
    "sim_declared_counts_note",
    "sim_image_size_problem",
    "sim_layout_counts_problem",
    "to_device",
    "BlendMode",
    "MaskedNccOptions",
    "StitchLayout",
    "StitchOptions",
    "TileMatch",
    "TranslationResult",
    "fuse_tiles",
    "masked_ncc",
    "next_fast_fft_size",
    "optimize_tile_positions",
    "plan_stitch",
    "register_tile_pair",
    "register_translation_masked",
    "stitch_tiff_tiles",
    "write_tiff",
]
