#!/bin/bash
# Fake sacct: `sacct -n -X -P -j <id> -o State,ExitCode`.
set -u
dir="${FAKE_SLURM_DIR:?}"
id=""
while [ $# -gt 0 ]; do case "$1" in -j) id="$2"; shift 2 ;; *) shift ;; esac; done
[ -f "$dir/$id.state" ] && echo "$(cat "$dir/$id.state")|0:0"
